version: '3.8'

services:
  udp-joker:
    image: incept1on/udp-joker:master
    env_file:
      - .env
    volumes:
      - ./lists.json:/app/lists.json
      - ./notifications.json:/app/notifications.json
    restart: on-failure
    environment:
      - TZ=Europe/Moscow
