name: Deploy to Server

on:
  workflow_run:
    workflows: [Build and Push to DockerHub and also intall Docker]
    types: [completed]
  workflow_dispatch:

env:
  DOCKER_COMPOSE_FILE: docker-compose.yaml
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOY_PATH: /home/${{ secrets.SSH_USER }}/app

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Create deployment directory on server
      run: |
        ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "mkdir -p $DEPLOY_PATH"
    
    - name: Create .env file on server
      run: |
        ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "touch $DEPLOY_PATH/.env"
    
    - name: Write Telegram token to .env file on server
      run: |
        ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "echo 'TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}' > $DEPLOY_PATH/.env"

    - name: Copy docker-compose file to server
      run: |
        scp -P ${{ secrets.SSH_PORT || '22' }} \
          $DOCKER_COMPOSE_FILE \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_PATH/

    - name: Copy environment files if they exist
      run: |
        if [ -f ".env" ]; then
          scp -P ${{ secrets.SSH_PORT || '22' }} \
            .env \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_PATH/
        fi
        # Copy any .env.* files
        for env_file in .env.*; do
          if [ -f "$env_file" ]; then
            scp -P ${{ secrets.SSH_PORT || '22' }} \
              "$env_file" \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$DEPLOY_PATH/
          fi
        done

    - name: Deploy application
      run: |
        ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd $DEPLOY_PATH &&
          docker-compose -f $DOCKER_COMPOSE_FILE down &&
          docker-compose -f $DOCKER_COMPOSE_FILE pull &&
          docker-compose -f $DOCKER_COMPOSE_FILE up -d
        "

    - name: Verify deployment
      run: |
        ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd $DEPLOY_PATH &&
          docker-compose -f $DOCKER_COMPOSE_FILE ps &&
          echo 'Deployment completed successfully!'
        "
