name: Terraform Plan and Apply

on:
  push:
    branches: [ master ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'terraform/**'
  workflow_dispatch:

env:
  TF_VERSION: "1.11.4"
  YC_TOKEN: "${{ secrets.YC_TOKEN }}"
  YC_CLOUD_ID: "${{ secrets.YC_CLOUD_ID }}"
  YC_FOLDER_ID: "${{ secrets.YC_FOLDER_ID }}"
  YC_ZONE: "ru-central1-b"

defaults:
  run:
    working-directory: ./terraform 

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Validate Terraform installation
      run: |
        terraform version

    - name: Install Yandex Cloud CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash 

    - name: Validate yc installation
      run: |
        ${HOME}/yandex-cloud/bin/yc version

    - name: Configure Yandex Cloud credentials
      run: |
        ${HOME}/yandex-cloud/bin/yc config profile create default
        ${HOME}/yandex-cloud/bin/yc config set token $YC_TOKEN
        ${HOME}/yandex-cloud/bin/yc config set cloud-id $YC_CLOUD_ID
        ${HOME}/yandex-cloud/bin/yc config set folder-id $YC_FOLDER_ID
        ${HOME}/yandex-cloud/bin/yc config set compute-default-zone $YC_ZONE
        
        ${HOME}/yandex-cloud/bin/yc config list
        
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="access_key=${{ secrets.YC_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.YC_SECRET_KEY }}"
    
    - name: Create file with ssh private key
      run: |
        mkdir -p ${HOME}/.ssh
        touch ${HOME}/.ssh/id_ed25519.pub
        echo -n "${{ secrets.SSH_PRIVATE_KEY }}" > ${HOME}/.ssh/id_ed25519.pub

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve